name: SonarCloud + Docker Hub
on:
  push:
    branches:
      - develop

jobs:
  # SONARCLOUD
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=22-BrandonGuerrero_S11_AP7_Reto
            -Dsonar.organization="Brandon Guerrero"
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # DOCKER HUB
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarcloud  # Ensure the SonarCloud job completes first
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/t02_translate_fe:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/t02_translate_fe:latest
